// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float> _CountryIndicesTex;
SamplerState country_point_clamp;

RWStructuredBuffer<float> _Result;

float2 uv;


[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float countryIndex = _CountryIndicesTex.SampleLevel(country_point_clamp, uv, 0);
    _Result[0] = countryIndex;
}